### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by fredrikhanssonsk** [netcore-jsa/unimus-backup-exporter#10]
Hey, 

Tried to use the script and Im using fs as destination. 
Edited the .env file with server adres, api and set backup type. 

But i get the following error: ./unimus-backup-exporter.sh: line 302: [: ==: unary operator expected
ERROR: Unable to connect to unimus server

Im running the script on the same server as Unimus are installed on and using this as address: unimus_server_address="http://localhost:8085"

Any tips how to troubleshoot this?

**Comment by AlexandrePoix** [comment]
Try :  if [ "$status" == "OK" ]; then
Fixed it for me

**Comment by fredrikhanssonsk** [comment]
> Try : if [ "$status" == "OK" ]; then Fixed it for me

This just made alot more errors for me, however different ones... 

./unimus-backup-exporter.sh: line 2: $'\r': command not found
./unimus-backup-exporter.sh: line 4: $'\r': command not found
./unimus-backup-exporter.sh: line 5: $'\r': command not found
./unimus-backup-exporter.sh: line 7: syntax error near unexpected token `$'{\r''
'/unimus-backup-exporter.sh: line 7: `function echoGreen(){

**Comment by tomaskir** [comment]
@fredrikhanssonsk this sounds like line ending issues - did you edit the script on Windows and transfer the files back to Linux? In such case, Windows sets line endings to `\r\n` (CRLF), but Linux expects `\n` (LF).

**Comment by fredrikhanssonsk** [comment]
Success! 

Thanks for your help fellas. 
I edited the files on a Windows and executed them via Linux subsystem in Windows. Did all the edits via nano in the subsystem, worked right away. 

Getting device data
Getting Device Information
Exporting latest backups
103 backups exported
Export successful
Script finished
