### ISSUE TITLE
syntax error when running the script as a cron job

### ISSUE THREAD

**Issue by 612wong** [netcore-jsa/unimus-backup-exporter#5]
Hi there, it's me again.

I tried to run the script as a cron job and found it returned me a syntax error.
Wondering if it requires some sort of compatbility to run it.

/home/"username"/unimus-backup-exporter-main/unimus-backup-exporter.sh: line 83: syntax error near unexpected token `<'
/home/"username"/unimus-backup-exporter-main/unimus-backup-exporter.sh: line 83: `                           read -a value < <(echo $(jq -e ".data[$data] | .id, .address" <<< $contents))'

Below is the statement in the cron job.

0 0,8,16 * * * /home/"username"/unimus-backup-exporter-main/unimus-backup-exporter.sh

**Comment by tomaskir** [comment]
@Twooey is this due to the bug fixed in dbeb435d855a59cfd7d3ed506a774560dc65f985?

**Comment by Twooey** [comment]
I don't believe so. I'm working on reproducing it.

**Comment by Twooey** [comment]
@612wong  Could you try running the attached script? 

[unimus-backup-exporter.zip](https://github.com/netcore-jsa/unimus-backup-exporter/files/7489620/unimus-backup-exporter.zip)
.

**Comment by 612wong** [comment]
@Twooey thanks for looking into this. I wanna close this issue because I have difficult to work on this integration with the Unimus we are running in the enterprise network.

Anyways, much appreciate for your attention and help over the past few weeks.
